### ISSUE TITLE
Improve 'open file' handling

### ISSUE THREAD

**Issue by sepulzera** [NinjaPewPew/CVS-History-Viewer#38]
Open a CVS-project as directory and select a commit. To this commit, the changed file(s) and their revisions are displayed in a list and can be selected for a diff view.

1.) Via double-click on **the current revision** of a file, it will be opened in an external editor of choice. I am not quite sure whether it is just a bug, that older revisions can not be opened, or a technical limitation. At least, it is not visible to the user, that this item is not interactive (UX issue).

2.) Furthermore, the double-click event handler appears to be **attached to the view**, instead of the list item. The current revision will open when double-clicking **anywhere** inside of the view. This is very confusing and should be fixed.

3.) Edit: It wasn't inuitive to me, that the files can be opened via double-click. There should be some indicator. Eventually a slightly changed highlight-color for the interactive file items would do the trick.

**Comment by FaithfulDev** [comment]
Thank you for the feedback.

1. Double-Click opens the current revision, that works as Intended. It's planed to extend this functionality via issue #9.
2. That's a **bug**. Sadly It's not as straightforward to implement as one might think.
3. Both the double-click and the future context menu are or will be discoverable via experimentation. Double-click to open files is a rather common mechanic, so I think it's fair to say that eventually user will find it. I think that's perfectly fine. Since they are all interactive, I don't see how it would be helpful to change their visual appearance.

**Comment by FaithfulDev** [comment]
This issue will be used to address point number 2.
